version: '4'

services:
  consumer:
    environment:
      - "KAFKA_HOST=kafka"
    build:
      context: consumer
      dockerfile: Dockerfile
    depends_on:
      - producer
    networks:
      - common-network
    ports:
      - 8082:8080
  producer:
    environment:
      - "KAFKA_HOST=kafka"
    build:
      context: producer
      dockerfile: Dockerfile
    depends_on:
      - cloud-config
    networks:
      - common-network
    ports:
      - 8081:8081
  cloud-config:
    build:
      context: cloud-config-server
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - common-network
    ports:
      - 8888:8888

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - common-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - common-network
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
      image: postgres:latest
      restart: always
      depends_on:
        - cloud-config
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=consumer_db
      ports:
        - 5432:5432
      networks:
        - common-network
      volumes:
        - postgres:/var/lib/postgresql/data

#  auth-service:
#    container_name: auth-service
#    image: keycloak/keycloak:26.0.5
#    environment:
#      KC_DB: postgres
#      KC_DB_USER: keycloak
#      KC_DB_PASSWORD: keycloak
#      KC_DB_URL: "jdbc:postgresql://auth-db:5432/keycloak"
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_LOG_LEVEL: DEBUG
#      KC_LOG_CONSOLE_COLOR: true
#    ports:
#      - 8080:8080
#    depends_on:
#      - auth-db
#    command:
#      - "start-dev"
#    networks:
#      - common-network
#  auth-db:
#    container_name: auth-db
#    image: postgres:16-alpine
#    depends_on:
#      - postgres
#    volumes:
#      - data_postgres_auth:/var/lib/postgres/auth
#    environment:
#      POSTGRES_PASSWORD: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_DB: keycloak
#    ports:
#      - 5432:5432
#    networks:
#      - common-network
#    restart: unless-stopped

volumes:
  postgres:
#  data_postgres_auth:

networks:
  common-network:
    driver: bridge