spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8085/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8085/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: qYxCg1dtoYiReTQPgFfIgJyZPbyi7Vy0
            authorization-grant-type: authorization_code
            scope: openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: producer-service
          uri: http://producer:8081
          predicates:
            - Path=/post/**
#        - id: caller-service
#          uri: http://localhost:8020
#          predicates:
#            - Path=/caller/**