spring:
  application:
    name: consumer
  profiles:
    active: consumer
  config:
    import: configserver:http://cloud-config:8888
#  config:
#    import: "optional:configserver:"
  cloud:
    config:
      uri: http://cloud-config:8888
      fail-fast: true

#  kafka:
#    bootstrap-servers: ${KAFKA_HOST:localhost}:29092
#    consumer:
#      group-id: ${spring.application.name}
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            type:
#              mapping: producer:org.taskmngr.dto.MassageDto


#    producer:
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
##          json:
##            type:
##              mapping: producer:org.taskmngr.dto.MassageDto

#consumer:
#  kafka:
#    id:
#      topic: 34
#    topic:
#      in: topic-message
#      out: order-message