spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: consumer
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: producer:org.taskmngr.dto.MassageDto
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/consumer_db
    username: postgres
    password: postgres
consumer:
  kafka:
    id:
      topic: 34
    topic:
      in: topic-message
      out: order-message