spring:
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      group-id: producer
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: producer:org.taskmngr.dto.MassageDto
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/consumer_db
    username: postgres
    password: postgres
producer:
  kafka:
    id:
      topic: 34
    topic:
      in: topic-message
      out: order-message